# Generated by Django 5.2.6 on 2025-10-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bussinessaccount',
            name='Photo',
            field=models.FileField(upload_to='business_photos/'),
        ),
        migrations.AlterField(
            model_name='bussinessaccount',
            name='Proof',
            field=models.FileField(upload_to='business_proofs/'),
        ),
    ]
