# Generated by Django 5.2.6 on 2025-10-16 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_bussinessaccount_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='Photo',
            field=models.FileField(upload_to='facility_photos/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Photo',
            field=models.FileField(upload_to='product_photos/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='Photo',
            field=models.FileField(upload_to='service_photos/'),
        ),
    ]
