# Generated by Django 5.2.6 on 2025-10-18 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_facility_photo_alter_product_photo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='SHOP',
            new_name='BUSSINESSACCOUNT',
        ),
    ]
