# Generated by Django 5.2.6 on 2025-10-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_shop_product_bussinessaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='Offername',
            field=models.CharField(max_length=100),
        ),
    ]
