# Generated by Django 5.2.6 on 2025-10-20 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_offers_offername'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Stock',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
