# Generated by Django 5.2.6 on 2025-10-20 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_product_stock_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='USER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.useraccount'),
        ),
    ]
