# Generated by Django 5.2.6 on 2025-10-20 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_productreview_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialisation',
            name='FITNESS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bussinessaccount'),
        ),
    ]
