# Generated by Django 5.2.6 on 2025-10-21 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_specialisation_fitness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility',
            name='FITNESS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bussinessaccount'),
        ),
    ]
