from django.contrib import admin
from django.urls import path, include

from myapp import views

urlpatterns = [
    path('', views.loginindex),
    path('loginindex', views.loginindex),
    path('logoutss', views.logoutss),
    path('adminhome', views.admin_home),
    path('admins_changepassword', views.admins_changepassword),
    path('admin_verify_buissness', views.admin_verify_buissness),
    path('admin_approve_buissness/<id>', views.admin_approve_buissness),
    path('admin_reject_buissness/<id>', views.admin_reject_buissness),
    path('admin_approved_buissness', views.admin_approved_buissness),
    path('admin_add_category', views.admin_add_category),
    path('admin_view_category', views.admin_view_category),
    path('admin_view_complaints_search', views.admin_view_complaints_search),
    path('admin_edit_category/<id>', views.admin_edit_category),
    path('admin_delete_category/<id>', views.admin_delete_category),
    path('admin_reply_complaints/<id>', views.admin_reply_complaints),
    path('admin_view_complaints/', views.admin_view_complaints),
    path('admin_view_users/', views.admin_view_users),
    path('admin_service_review/', views.admin_service_review),
    path('admin_appFeedBack/', views.admin_appFeedBack),
    # ==================================================================
    path('BuissnessAccount_Reg', views.BuissnessAccount_Reg),
    path('service_provider_home', views.service_provider_home),
    path('service_changepassword', views.service_changepassword),
    path('service_providerProfile', views.service_providerProfile),
    path('serviceProvider_Edit_profile', views.serviceProvider_Edit_profile),
    path('provider_viewCategory', views.provider_viewCategory),
    path('provider_addServices', views.provider_addServices),
    path('provider_viewServices/', views.provider_viewServices),
    path('provider_edit_services/<id>', views.provider_edit_services),
    path('provider_delete_services/<id>', views.provider_delete_services),
    path('provider_view_review/<id>', views.provider_view_review),
    path('provider_edit_availability/<id>', views.provider_edit_availability),
    path('provider_delete_availability/<id>', views.provider_delete_availability),
    path('provider_Requests_Approve/<id>', views.provider_Requests_Approve),
    path('provider_Requests_Reject/<id>', views.provider_Requests_Reject),
    path('provider_addavailability', views.provider_addavailability),
    path('provider_viewStatus', views.provider_viewStatus),
    path('provider_viewRequests', views.provider_viewRequests),
    path('provider_viewRequests_search', views.provider_viewRequests_search),
    path('provider_viewApproved_Requests', views.provider_viewApproved_Requests),



    path('prochat/<id>/', views.chat3),
    path('provider_chat_view/', views.provider_chat_view),
    path('provider_chat_send/<msg>/', views.provider_chat_send),


#     ===================================================================================

    path('shop_home', views.shop_home),
    # path('shopss_home/', views.shopss_home),
    path('shop_changepassword', views.shop_changepassword),
    path('shop_Profile', views.shop_Profile),
    path('shop_Edit_profile', views.shop_Edit_profile),
    path('shop_add_products', views.shop_add_products),
    path('shop_view_products', views.shop_view_products),
    path('shop_edit_products/<id>', views.shop_edit_products),
    path('shop_delete_products/<id>', views.shop_delete_products),
    path('shop_add_offers/<id>', views.shop_add_offers),
    path('shop_delete_offers/<id>', views.shop_delete_offers),
    path('shop_edit_offers/<id>', views.shop_edit_offers),
    path('shop_view_offers/', views.shop_view_offers),
    path('shop_add_stock/', views.shop_add_stock),
    path('shop_view_stock/', views.shop_view_stock),
    path('shop_delete_stock/<id>', views.shop_delete_stock),
    path('shop_view_productreview/<id>', views.shop_view_productreview),
    path('shop_edit_stock/<id>', views.shop_edit_stock),
    path('shop_view_orders/', views.shop_view_orders),

    path('chat2/<id>', views.chat2),
    path('shop_chat_view/', views.shop_chat_view),
    path('shop_chat_send/<msg>/', views.shop_chat_send),



    # ===============================================================
    path('fitness_home/', views.fitness_home),
    path('fitness_changepassword/', views.fitness_changepassword),
    path('fitness_Profile/', views.fitness_Profile),
    path('fitness_Edit_profile/', views.fitness_Edit_profile),
    path('fitness_add_specialisation/', views.fitness_add_specialisation),
    path('fit_view_specialisations/', views.fit_view_specialisations),
    path('fitness_edit_specialisation/<id>', views.fitness_edit_specialisation),
    path('fitness_delete_specialisation/<id>', views.fitness_delete_specialisation),
    path('fitness_add_Services/', views.fitness_add_Services),
    path('fitness_viewServices/', views.fitness_viewServices),
    path('fitness_delete_services/', views.fitness_delete_services),
    path('fitness_edit_services/<id>', views.fitness_edit_services),
    path('fitness_view_review/<id>', views.fitness_view_review),
    path('fit_addavailability/', views.fit_addavailability),
    path('fitness_viewStatus/', views.fitness_viewStatus),
    path('fitness_edit_availability/<id>', views.fitness_edit_availability),
    path('fitness_delete_availability/<id>', views.fitness_delete_availability),
    path('fitness_add_facility', views.fitness_add_facility),
    path('fitness_view_facility', views.fitness_view_facility),
    path('fitness_edit_facility/<id>', views.fitness_edit_facility),
    path('fitness_delete_facility/<id>', views.fitness_delete_facility),
    path('fitness_add_offers/', views.fitness_add_offers),
    path('fitness_view_offers/', views.fitness_view_offers),
    path('fitness_edit_offers/<id>', views.fitness_edit_offers),
    path('fitness_delete_offers/<id>', views.fitness_delete_offers),
    path('fitness_add_Slots/<id>', views.fitness_add_Slots),
    path('fitness_edit_Slots/<id>', views.fitness_edit_Slots),
    path('fintness_delete_slot/<id>', views.fintness_delete_slot),
    path('fitness_view_appointments/', views.fitness_view_appointments),
    path('view_added_SLOT/', views.view_added_SLOT),
    path('fintness_approve_appointments/<id>', views.fintness_approve_appointments),
    path('fintness_reject_appointments/<id>', views.fintness_reject_appointments),
    path('fitness_view_approved/', views.fitness_view_approved),
    path('fitness_view_payments/', views.fitness_view_payments),
    path('chat1/<id>', views.chat1),
    path('fit_chat_view/', views.fit_chat_view),
    path('fit_chat_send/<msg>/', views.fit_chat_send),
#     =============================USER MODULE
    path('user_login/', views.user_login),
    path('Customer_reg/', views.Customer_reg),
    path('customer_viewprofile/', views.customer_viewprofile),
    path('cust_editprofile/', views.cust_editprofile),
    path('userchangepassword/', views.userchangepassword),
    path('user_view_centers/', views.user_view_centers),
    path('user_view_services/', views.user_view_services),
    path('user_view_availability/', views.user_view_availability),
    path('service_booking/', views.service_booking),
    path('user_view_requeststatus/', views.user_view_requeststatus),
    path('servicepayment/', views.cartpayment),
    path('user_view_facilities/', views.user_view_facilities),
    path('user_sendFeedback/', views.user_sendFeedback),
    path('user_sendComplaints/', views.user_sendComplaints),
    path('user_view_reply/', views.user_view_reply),
    path('user_view_slot/', views.user_view_slot),
    path('slot_booking/', views.slot_booking),
    path('user_view_booked_slots/', views.user_view_booked_slots),
    path('slotpayment/', views.slotpayment),
    path('user_view_paymentDetails/', views.user_view_paymentDetails),
    path('user_view_offers/', views.user_view_offers),
    path('addtocart/', views.addtocart),
    path('user_view_cart/', views.user_view_cart),
    path('deletefromcart/', views.deletefromcart),
    path('cartpaymentss/', views.cartpaymentss),
    path('user_view_products/', views.user_view_products),
    path('user_view_orders/', views.user_view_orders),
    path('sendproductreview/', views.sendproductreview),
    path('sendservicereview/', views.sendservicereview),
    path('chat/', views.chatss),
    path('user_view_fitnescenters/', views.user_view_fitnescenters),
    path('user_view_fitnescentersoffers/', views.user_view_fitnescentersoffers),
    path('user_chat_send/', views.user_chat_send),
    path('chat_view_user/', views.chat_view_user),
    path('user_view_allservices/', views.user_view_allservices),


    path('ForgotPassword/', views.ForgotPassword),
    path('forgotpasswordflutter/', views.forgotpasswordflutter),
    path('verifyOtpflutterPost/', views.verifyOtpflutterPost),
    path('changePasswordflutter/', views.changePasswordflutter),
    path('forgotPassword_otp/', views.forgotPassword_otp),
    path('verifyOtp/', views.verifyOtp),
    path('verifyOtpPost/', views.verifyOtpPost),
    path('new_password/', views.new_password),
    path('changePassword/', views.changePassword),
    path('user_view_all_payments/', views.user_view_all_payments),



]


